"""add description to experiences

Revision ID: 05009c05a7c8
Revises: 0bbae65f4495
Create Date: 2026-10-04 15:23:22.305708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05009c05a7c8'
down_revision: Union[str, Sequence[str], None] = '0bbae65f4495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiences', sa.Column('description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'resume_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'resume_profiles', type_='foreignkey')
    op.drop_column('experiences', 'description')
    # ### end Alembic commands ###
