"""add embedding column

Revision ID: b0dff8e6f29e
Revises: 05009c05a7c8
Create Date: 2026-10-07 15:21:12.197377

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0dff8e6f29e'
down_revision: Union[str, Sequence[str], None] = '05009c05a7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'achievements', 'resume_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.add_column('experiences', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.create_foreign_key(None, 'experiences', 'resume_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.create_foreign_key(None, 'projects', 'resume_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.add_column('skills', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.create_foreign_key(None, 'skills', 'resume_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'embedding')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'embedding')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_column('experiences', 'embedding')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    # ### end Alembic commands ###
